package com.lib_greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lib_greendao.model.DBMedicineClockList;
import com.lib_greendao.model.DBTemperature;

import com.lib_greendao.dao.DBMedicineClockListDao;
import com.lib_greendao.dao.DBTemperatureDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBMedicineClockListDaoConfig;
    private final DaoConfig dBTemperatureDaoConfig;

    private final DBMedicineClockListDao dBMedicineClockListDao;
    private final DBTemperatureDao dBTemperatureDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBMedicineClockListDaoConfig = daoConfigMap.get(DBMedicineClockListDao.class).clone();
        dBMedicineClockListDaoConfig.initIdentityScope(type);

        dBTemperatureDaoConfig = daoConfigMap.get(DBTemperatureDao.class).clone();
        dBTemperatureDaoConfig.initIdentityScope(type);

        dBMedicineClockListDao = new DBMedicineClockListDao(dBMedicineClockListDaoConfig, this);
        dBTemperatureDao = new DBTemperatureDao(dBTemperatureDaoConfig, this);

        registerDao(DBMedicineClockList.class, dBMedicineClockListDao);
        registerDao(DBTemperature.class, dBTemperatureDao);
    }
    
    public void clear() {
        dBMedicineClockListDaoConfig.clearIdentityScope();
        dBTemperatureDaoConfig.clearIdentityScope();
    }

    public DBMedicineClockListDao getDBMedicineClockListDao() {
        return dBMedicineClockListDao;
    }

    public DBTemperatureDao getDBTemperatureDao() {
        return dBTemperatureDao;
    }

}
