package com.lib_greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lib_greendao.model.DBMedicineClockList;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DBMEDICINE_CLOCK_LIST".
*/
public class DBMedicineClockListDao extends AbstractDao<DBMedicineClockList, Long> {

    public static final String TABLENAME = "DBMEDICINE_CLOCK_LIST";

    /**
     * Properties of entity DBMedicineClockList.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Time = new Property(1, long.class, "time", false, "TIME");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property Repeat = new Property(3, String.class, "repeat", false, "REPEAT");
        public final static Property Json = new Property(4, String.class, "json", false, "JSON");
        public final static Property IsOpen = new Property(5, boolean.class, "isOpen", false, "IS_OPEN");
    }


    public DBMedicineClockListDao(DaoConfig config) {
        super(config);
    }
    
    public DBMedicineClockListDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DBMEDICINE_CLOCK_LIST\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TIME\" INTEGER NOT NULL ," + // 1: time
                "\"TITLE\" TEXT," + // 2: title
                "\"REPEAT\" TEXT," + // 3: repeat
                "\"JSON\" TEXT," + // 4: json
                "\"IS_OPEN\" INTEGER NOT NULL );"); // 5: isOpen
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DBMEDICINE_CLOCK_LIST\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DBMedicineClockList entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getTime());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String repeat = entity.getRepeat();
        if (repeat != null) {
            stmt.bindString(4, repeat);
        }
 
        String json = entity.getJson();
        if (json != null) {
            stmt.bindString(5, json);
        }
        stmt.bindLong(6, entity.getIsOpen() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DBMedicineClockList entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getTime());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String repeat = entity.getRepeat();
        if (repeat != null) {
            stmt.bindString(4, repeat);
        }
 
        String json = entity.getJson();
        if (json != null) {
            stmt.bindString(5, json);
        }
        stmt.bindLong(6, entity.getIsOpen() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DBMedicineClockList readEntity(Cursor cursor, int offset) {
        DBMedicineClockList entity = new DBMedicineClockList( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // time
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // repeat
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // json
            cursor.getShort(offset + 5) != 0 // isOpen
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DBMedicineClockList entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTime(cursor.getLong(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRepeat(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setJson(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setIsOpen(cursor.getShort(offset + 5) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DBMedicineClockList entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DBMedicineClockList entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DBMedicineClockList entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
